import createPWA from 'next-pwa';

const withPWA = createPWA({
  dest: 'public',
  disable: process.env.NODE_ENV === 'development',
  register: true,
  skipWaiting: true,
});

const nextConfig = {
  output: 'standalone', // PM2로 구동하기 좋게 최소 실행 번들 생성
  eslint: {
    // 프로덕션 빌드 시 ESLint 에러 무시 (임시 조치)
    ignoreDuringBuilds: true,
  },
  typescript: {
    // 프로덕션 빌드 시 TypeScript 에러 무시 (필요한 경우)
    ignoreBuildErrors: true,
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: `frame-src https://smartfarming.live https://dn8wklnt2iid2.cloudfront.net http://localhost:3000;`
          },    
        ]
      }
    ]
  }
}

export default withPWA(nextConfig);