name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy using SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-XXXXXXXXXXXXX" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ubuntu/smartfarming-ai",
              "git pull origin main",
              "echo \"NEXT_PUBLIC_DATABASE_URL=${{ secrets.NEXT_PUBLIC_DATABASE_URL }}\" > .env",
              "echo \"NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}\" >> .env",
              "echo \"CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}\" >> .env",
              "echo \"NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}\" >> .env",
              "echo \"NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}\" >> .env",
              "echo \"NEXT_PUBLIC_REPLICATE_API_TOKEN=${{ secrets.NEXT_PUBLIC_REPLICATE_API_TOKEN }}\" >> .env",
              "echo \"NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}\" >> .env",
              "yarn install",
              "NODE_OPTIONS=\"--max-old-space-size=2048\" yarn build",
              "pm2 restart all"
            ]' \
            --output-s3-bucket-name "your-s3-bucket-name" \
            --output-s3-key-prefix "deploy-logs"